apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: test-cluster
  region: us-east-1
  version: "1.29" # pick the latest supported version

vpc:
  cidr: 10.0.0.0/16 # optional, eksctl can create automatically
  nat:
    gateway: Single # cost saving for test/prod-lite

# IAM service accounts for cluster addons
iam:
  withOIDC: true
  serviceAccounts:
    - metadata:
        name: ebs-csi-controller-sa
        namespace: kube-system
      wellKnownPolicies:
        ebsCSIController: true

# EKS Addons
addons:
  - name: eks-pod-identity-agent
    resolveConflicts: overwrite
    version: latest
  - name: aws-ebs-csi-driver
    resolveConflicts: overwrite
    version: latest
  - name: vpc-cni
    resolveConflicts: overwrite
    version: latest
    podIdentityAssociations:
      - serviceAccountName: aws-node
        namespace: kube-system
        permissionPolicyARNs:
          - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy

managedNodeGroups:
  - name: system-nodes
    instanceType: t3.small
    desiredCapacity: 1
    minSize: 1
    maxSize: 1
    labels:
      role: system
      workload-type: system
      namespace-preference: system
    taints:
      - key: "node-role.kubernetes.io/system"
        value: "true"
        effect: "NoSchedule"
    iam:
      withAddonPolicies:
        autoScaler: true
        externalDNS: true
        certManager: true
        ebs: true
    ssh:
      allow: false

  - name: database-nodes
    instanceType: t3.small
    desiredCapacity: 1
    minSize: 1
    maxSize: 2
    labels:
      role: database
      workload-type: database
      namespace-preference: database
    taints:
      - key: "workload-type"
        value: "database"
        effect: "NoSchedule"
    iam:
      withAddonPolicies:
        autoScaler: true
        externalDNS: true
        certManager: true
        ebs: true
    ssh:
      allow: false

  - name: public-nodes
    instanceType: t3.small
    desiredCapacity: 1
    minSize: 1
    maxSize: 2
    labels:
      role: public
      workload-type: public
      namespace-preference: public
    iam:
      withAddonPolicies:
        autoScaler: true
        externalDNS: true
        certManager: true
        ebs: true
    ssh:
      allow: false
